backend/backend/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('issueTracker.urls')),
    path('accounts/', include('accounts.urls')),
    path('', home),
    # path('about/', TemplateView.as_view(template_name='about.html')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/issueTracker/urls.py
from django.urls import path, re_path
from . import views

app_name = 'issueTracker'

urlpatterns = [
    path('', views.project_list, name='projects_list'),
    path('<slug:slug>/issues/', views.issues, name='issues'),
    path('<slug:slug>/create-issue/', views.create_issue, name='create_issue'),
    path('<slug:slug>/issue/<int:pk>/', views.issue, name='issue'),
    path('<slug:slug>/edit/<int:pk>/', views.edit, name='edit'),
    path('my-tasks_assigned/', views.tasks_assigned_to_me, name='my_tasks_assigned'),
    path('my-tasks_created/', views.tasks_created_by_me, name='my_tasks_created'),
    path('all_todo/', views.all_todo, name='all_todo'),
]

backend/issueTracker/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
class Project(models.Model):
    project_name = models.CharField(max_length=30, primary_key=True)
    Pt = (
        ('DA','destopApp'),
        ('WA','webApp'),
        ('AA','androidApp')
    )
    project_type = models.CharField(max_length=2, choices=Pt)
    slug = models.CharField(max_length=20)

    def __str__(self):
        return self.project_name


class Issues(models.Model):
    # many issues to one project
    # and an issue can only be in one project
    project = models.ForeignKey(Project, on_delete=models.CASCADE)  # default=current_project
    isst = (
        ('B', 'Bug'),
        ('I', 'Improvement'),
        ('F', 'Feature'),
        ('E', 'Epic')
    )
    issue_type = models.CharField(max_length=1, choices=isst)
    title = models.CharField(max_length=100)  # or summary
    description = models.TextField(max_length=500)
    created_date = models.DateTimeField(
        "date created",
        default = datetime.now()
        )
    fixed_date = models.DateTimeField("date fixed", blank=True, null=True)
    activity = models.DateTimeField("last updated date", blank=True, null=True)
    # many to many??, issue can have many status, and a status would have many issue
    # but also status options are limited
    stat = (
        ('1', 'Todo'),
        ('2', 'In progress'),
        ('3', 'In review'),
        ('4', 'Done')
    )
    status = models.CharField(
        max_length=2, 
        choices=stat,
        default='1')
    # an issue can only have one creator, so still many to one,
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="created_by")
    # an issue can be assigned to one user at a time
    assigned_to = models.ForeignKey(
        User, on_delete=models.CASCADE, 
        related_name="assigned_to", 
        blank=True, 
        null=True
        )
    prior = (
        ('1', 'Highest'),
        ('2', 'High'),
        ('3', 'Medium'),
        ('4', 'Lower'),
        ('5', 'Lowest'),
        ('6', 'Done'),
    )
    priority = models.CharField(max_length=2, choices=prior, default='3')

    class Meta:
        ordering = ['priority', 'status']

    def __str__(self):
        return self.title

backend/issueTracker/forms.py
from .models import Issues, Project
from django import forms

class CreateIssue(forms.ModelForm):
    class Meta:
        model = Issues
        fields = (
            'project', 
            'issue_type',
            'title', 
            'description', 
            'created_date',
            'fixed_date',
            'activity',
            'status',
            'created_by',
            'assigned_to',
            'priority',
        )

        # widgets = {
        #     'created_date': forms.DateTimeInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-target': '#datetimepicker1'
        #     }),
        #     'fixed_date': forms.DateTimeInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-target': '#datetimepicker2'
        #     }),
        #     'activity': forms.DateTimeInput(attrs={
        #         'class': 'form-control datetimepicker-input',
        #         'data-target': '#datetimepicker3'
        #     }),
        # }

        # input_formats={
        #     'created_date': ['%d/%m/%Y %#I:%M %p'],
        #     'fixed_date': ['%d/%m/%Y %#I:%M %p'],
        #     'activity': ['%d/%m/%Y %#I:%M %p'],
        # }
        
    
class CreateProject(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_name','project_type','slug']

backend/issueTracker/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Project, Issues
from .forms import CreateIssue, CreateProject
from django.contrib.auth.models import User


def project_list(request):
    projects = Project.objects.all()
    issues = []

    for project in projects:
        issues_p = project.issues_set.filter(status="1")[:3]
        issues.append(issues_p)
    return render(request, "issueTracker/index_.html", {
        'projects' : projects,
        'issues' : issues
    })


def issues(request, slug):
    project = Project.objects.get(slug = slug)
    return render(request, "issueTracker/issues.html", {'project':project})


@login_required(login_url='accounts:login')
def create_issue(request, slug):
    project = Project.objects.get(slug=slug)
    if request.method == 'POST':
        form = CreateIssue(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('issueTracker:issues', slug=project.slug)
    else:
        form = CreateIssue()
    return render(request, "issueTracker/create_issue.html", {
        'form':form,
        'project':project
        })


def issue(request, slug, pk):
    project = Project.objects.get(slug=slug)
    issue = project.issues_set.get(pk=pk)
    return render(request, "issueTracker/issue.html", {
        "issue":issue,
        'project':project
        })


@login_required(login_url='accounts:login')
def edit(request, slug, pk):
    project = Project.objects.get(slug=slug)
    issue = project.issues_set.get(pk=pk)
    form = CreateIssue(request.POST or None, instance=issue)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('issueTracker:issues', slug=project.slug)
    return render(request, "issueTracker/edit.html", {
        "issue":issue,
        'project':project,
        'form':form
        })


def tasks_assigned_to_me(request):
    projects = Project.objects.all()
    current_user = request.user
    if request.user.is_authenticated:
        issues = Issues.objects.filter(assigned_to=current_user)
        return render(request, "issueTracker/my_tasks_assigned.html", {
            "projects":projects,
            'issues':issues
            })
    return redirect("accounts:login")


def tasks_created_by_me(request):
    projects = Project.objects.all()
    current_user = request.user
    if request.user.is_authenticated:
        issues = Issues.objects.filter(created_by=current_user)
        return render(request, "issueTracker/my_tasks_created.html", {
            "projects":projects,
            'issues':issues
            })
    return redirect("accounts:login")


def all_todo(request):
    projects = Project.objects.all()
    current_user = request.user
    if request.user.is_authenticated:
        issues = Issues.objects.filter(created_by=current_user, status = '1')
        return render(request, "issueTracker/all_todo.html", {
            "projects":projects,
            'issues':issues
            })
    return redirect("accounts:login")

    

backend/issueTracker/templates/issueTracker/all_todo.html
{% extends 'base.html' %}
<!-- arguments past in from views
{
"projects":projects,
'issues':issues
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100">Tasks assigned to me</h5>
        </div>
    </div>
    {% for project in projects %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">
            {{project.project_name}}
        </h6>
        {% for issue in issues %}
            {% if issue.project == project %}
                {% if issue.status == "4" %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#73767a" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block done-issue">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% else %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#007bff" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block ">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</main>
{% endblock %}

backend/issueTracker/templates/issueTracker/create.html
{% extends 'base.html' %}
<!-- {
'form':form,
'project':project
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100"><a
                    href="{% url 'issueTracker:issues' issue.project %}">{{ project.project_name }}</a></h6>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <!-- <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6> -->
        <div class="media text-muted pt-3">
            <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Create">
            </form>
        </div>
        <!-- <small class="d-block text-right mt-3">
            <a href="#">...</a>
        </small> -->
    </div>
</main>

{% endblock %}

backend/issueTracker/templates/issueTracker/create_issue.html
{% extends 'base.html' %}
<!-- {
'form':form,
'project':project
} -->
{% block content %}
<main role="main" class="container">
    <div class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
            <div class="lh-100">
                <h5 class="mb-0 text-white lh-100"><a
                        href="{% url 'issueTracker:issues' project.slug %}">{{ project.project_name }}</a></h6>
            </div>
        </div>

        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <!-- <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6> -->
            <div class="media text-muted pt-3">
                <form class="site-form" action="{% url 'issueTracker:create_issue' project.slug %}" method="post"
                    enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'includes/bs4_form_.html' with form=form %}
                    <div class="container">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

backend/issueTracker/templates/issueTracker/edit.html
{% extends 'base.html' %}
<!-- {
"issue":issue,
'project':project
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100"><a
                    href="{% url 'issueTracker:issues' project.slug %}">{{ project.project_name }}</a></h6>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <!-- <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6> -->
        <div class="media text-muted pt-3">
            <form class="site-form" action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% include 'includes/bs4_form_.html' with form=form %}
                <div class="container">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        <!-- <small class="d-block text-right mt-3">
            <a href="#">...</a>
        </small> -->
    </div>
</main>

{% endblock %}

backend/issueTracker/templates/issueTracker/index.html
{% extends 'base.html' %}
{% load app_filters %}

{% block content %}
<main role="main" class="container">
    <div class="align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100">Projects</h6>
        </div>
    </div>
        {% for counter in projects|counters %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">
                {% with project=projects|index:counter %}
                <a href="{% url 'issueTracker:issues' project.slug %}">{{project.project_name}}</a>
            </h6>
            {% with issues_p=issues|index:counter %}
            {% for issue in issues_p %}
            <div class="media text-muted pt-3">
                <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                    <rect width="100%" height="100%" fill="#007bff" />
                </svg>
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="d-block text-gray-dark">
                        <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                    </strong>
                    {{issue.description}}
                    <span class="d-block b-right">{{issue.get_priority_display}}</span>
                    <span class="d-block b-right">{{issue.get_status_display}}</span>
                    <span class="d-block b-right">{{issue.created_date}}</span>
                </p>
            </div>
            {% endfor %}
            {% endwith %}
            {% endwith %}
        </div>
        {% endfor %}
</main>
{% endblock %}

backend/issueTracker/templates/issueTracker/index_.html
{% extends 'base.html' %}
{% load app_filters %}

{% block content %}
<main role="main" class="container mt-5">
    {% for counter in projects|counters %}

        {% with project=projects|index:counter %}

        <!-- project header -->
        <section class="jumbotron text-center pb-1">
            <div class="container">
                <h1 class="jumbotron-heading">
                    <a href="{% url 'issueTracker:issues' project.slug %}">{{project.project_name}}</a>
                </h1>
                <p class="lead text-muted">project sunmmary -- This is an issue-tracker|bug-tracker project that I wrote
                    in django. During the building process, I used the app itself to keep tracks of all issues that I
                    came across and all features that I want to implement. This process has made me dig deep into
                    Django, the MVC framework, bootstrap.</p>
                <div class="">
                    <a href="{% url 'issueTracker:issues' project.slug %}" class="btn btn-primary my-2">Go to
                        project</a>
                    <a href="{% url 'issueTracker:create_issue' project.slug %}" class="btn btn-secondary my-2">Add an
                        Issue</a>
                </div>
            </div>


            <div class="album py-5">
                <div class="container">
                    <div class="row">
                        {% with issues_p=issues|index:counter %}
                        {% for issue in issues_p %}
                        <div class="col-lg-4 d-flex align-items-stretch">
                            <div class="card mb-4 shadow-sm">
                                <svg class="bd-placeholder-img card-img-top" width="100%" height="150"
                                    xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
                                    focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                                    <!-- what is this title tag -->
                                    <title>{{issue.title}}</title>
                                    <rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%"
                                        fill="#eceeef" dy=".3em">{{issue.title}}</text>
                                </svg>
                                <div class="card-body d-flex flex-column justify-content-between">
                                    <p class="card-text">{{issue.description}}</p>

                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}"
                                                class="btn btn-sm btn-outline-secondary">View</a>

                                            <a href="{% url 'issueTracker:edit' project.slug issue.id %}"
                                                class="btn btn-sm btn-outline-secondary">Edit</a>
                                        </div>
                                        <small class="text-muted">{{issue.created_date}}</small>
                                    </div>


                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                    {% endwith %}
                </div>
            </div>
        </section>

    {% endfor %}
</main>

{% endblock %}

backend/issueTracker/templates/issueTracker/issue.html
{% extends 'base.html' %}
<!-- {
"issue":issue,
'project':project
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100"><a
                    href="{% url 'issueTracker:issues' project.slug %}">{{ project.project_name }}</a></h6>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">
            <a class="btn btn-light btn-block" href="{% url 'issueTracker:edit' project.slug issue.id %}"
                role="button">Edit</a>
        </h6>

        <div class="media text-muted pt-3 row">
            <div class="col-sm-3">
                <p class="d-block text-left font-weight-bold"> Title</p>
            </div>
            <div class="col-sm-9">
                <p class="d-block text-gray-dark text-left font-weight-bold">{{issue.title}}</p>
            </div>
        </div>
        <div class="media text-muted pt-3 row">
            <div class="col-sm-3">
                <p class="d-block text-left font-weight-bold"> Description</p>
            </div>
            <div class="col-sm-9">
                <p class="d-block text-left">{{issue.description}}</p>
            </div>
        </div>
        <div class="media text-muted pt-3 row">
            <div class="col-sm-3">
                <p class="d-block text-left font-weight-bold"> Created date</p>
                <p class="d-block text-left font-weight-bold"> Fixed date</p>
                <p class="d-block text-left font-weight-bold"> Acticity</p>
                <p class="d-block text-left font-weight-bold"> Created by</p>
                <p class="d-block text-left font-weight-bold"> Assigned to</p>
                <p class="d-block text-left font-weight-bold"> Status</p>
                <p class="d-block text-left font-weight-bold"> Priority</p>
            </div>
            <div class="col-sm-9">
                <p class="d-block text-left">{{issue.created_date}}</p>
                <p class="d-block text-left">{{issue.fixed_date}}</p>
                <p class="d-block text-left">{{issue.activity}}</p>
                <p class="d-block text-left">{{issue.created_by}}</p>
                <p class="d-block text-left">{{issue.assigned_to}}</p>
                <p class="d-block text-left">{{issue.get_status_display}}</p>
                <p class="d-block text-left">{{issue.get_priority_display}}</p>
            </div>
        </div>
        <small class="d-block text-right mt-3">
            <a href="#">...</a>
        </small>
    </div>
</main>
{% endblock %}

backend/issueTracker/templates/issueTracker/issues.html
{% extends 'base.html' %}
<!-- {'project':project} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100">{{ project.project_name }}</h6>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">
            <a class="btn btn-light btn-block" href="{% url 'issueTracker:create_issue' project.slug %}" role="button">
                create new issue
            </a>
        </h6>
        {% for issue in project.issues_set.all %}
        {% if issue.status == "4" %}
        <div class="media text-muted pt-3">
            <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                <rect width="100%" height="100%" fill="#73767a" />
            </svg>
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">
                    <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                </strong>
                <span class="d-block done-issue">{{issue.description}}</span>
                <span class="d-block b-right">{{issue.get_priority_display}}</span>
                <span class="d-block b-right">{{issue.get_status_display}}</span>
                <span class="d-block b-right">{{issue.created_date}}</span>
            </p>
            {% else %}
            <div class="media text-muted pt-3">
                <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                    <rect width="100%" height="100%" fill="#007bff" />
                </svg>
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="d-block text-gray-dark">
                        <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                    </strong>
                    {{issue.description}}
                    <span class="d-block b-right">{{issue.get_priority_display}}</span>
                    <span class="d-block b-right">{{issue.get_status_display}}</span>
                    <span class="d-block b-right">{{issue.created_date}}</span>
                </p>
                {% endif %}
            </div>
            {% endfor %}
            <small class="d-block text-right mt-3">
                <a href="#">...</a>
            </small>
        </div>
</main>
{% endblock %}

backend/issueTracker/templates/issueTracker/my_tasks_assigned.html
{% extends 'base.html' %}
<!-- arguments past in from views
{
"projects":projects,
'issues':issues
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100">Tasks assigned to me</h5>
        </div>
    </div>
    {% for project in projects %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">
            <a href="{% url 'issueTracker:issues' project.slug %}">{{project.project_name}}</a>
        </h6>
        {% for issue in issues %}
            {% if issue.project == project %}
                {% if issue.status == "4" %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#73767a" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block done-issue">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% else %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#007bff" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block ">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</main>
{% endblock %}

backend/issueTracker/templates/issueTracker/my_tasks_created.html
{% extends 'base.html' %}
<!-- arguments past in from views
{
"projects":projects,
'issues':issues
} -->
{% block content %}
<main role="main" class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm">
        <div class="lh-100">
            <h5 class="mb-0 text-white lh-100">Tasks created by me</h5>
        </div>
    </div>
    {% for project in projects %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">
            {{project.project_name}}
        </h6>
        {% for issue in issues %}
            {% if issue.project == project %}
                {% if issue.status == "4" %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#73767a" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block done-issue">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% else %}
                <div class="media text-muted pt-3">
                    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" role="img">
                        <rect width="100%" height="100%" fill="#007bff" />
                    </svg>
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="d-block text-gray-dark">
                            <a href="{% url 'issueTracker:issue' project.slug issue.id %}">{{issue.title}}</a>
                        </strong>
                        <span class="d-block ">{{issue.description}}</span>
                        <span class="d-block b-right">{{issue.get_priority_display}}</span>
                        <span class="d-block b-right">{{issue.get_status_display}}</span>
                        <span class="d-block b-right">{{issue.created_date}}</span>
                    </p>
                </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</main>
{% endblock %}