backend/accounts/urls.py
from django.urls import path
from .views import log_in, sign_up, log_out

app_name = "accounts"

urlpatterns = [
    path("signup/", sign_up, name="signup"),
    path("login/", log_in, name="login"),
    path("logout/", log_out, name="logout"),
]

backend/backend/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
from django.views.generic import TemplateView
from .views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('issueTracker.urls')),
    path('accounts/', include('accounts.urls')),
    path('', home),
    # path('about/', TemplateView.as_view(template_name='about.html')),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/issueTracker/urls.py
from django.urls import path, re_path
from . import views

app_name = 'issueTracker'

urlpatterns = [
    path('', views.project_list, name='projects_list'),
    path('<slug:slug>/issues/', views.issues, name='issues'),
    path('<slug:slug>/create-issue/', views.create_issue, name='create_issue'),
    path('<slug:slug>/issue/<int:pk>/', views.issue, name='issue'),
    path('<slug:slug>/edit/<int:pk>/', views.edit, name='edit'),
    path('my-tasks_assigned/', views.tasks_assigned_to_me, name='my_tasks_assigned'),
    path('my-tasks_created/', views.tasks_created_by_me, name='my_tasks_created'),
    path('all_todo/', views.all_todo, name='all_todo'),
]

backend/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>About me, a lot about me</h1>
</body>
</html>

backend/templates/base.html
{% load static from staticfiles %}


<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>We got Issues</title>

    <!-- bootsrap cdn -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Tempus Dominus -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />


    <!-- Custom styles for this template -->
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <style>
        .text-area {
            height: 180px;
        }
    </style>
</head>

<body class="bg-light pt-0">
    <header>
        <!-- callapse part -->
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row side-offset">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">
                            This is an issue-tracker|bug-tracker project that I wrote in django. During the building
                            process,
                            I used the app itself to keep tracks of all issues that I came across and all features that
                            I want
                            to implement. This process has made me dig deep into Django, the MVC framework, bootstrap.

                        </p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Skills</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Python & Django</a></li>
                            <li><a href="#" class="text-white">Javascript</a></li>
                            <li><a href="#" class="text-white">HTML & CSS</a></li>
                            <li><a href="#" class="text-white">Bootstrap</a></li>
                            <li><a href="#" class="text-white">MVC framework</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="navbar navbar-dark bg-dark shadow-sm ">
            <div class="container d-flex justify-content-between side-offset">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <i class="fas fa-rocket mr-3"></i>
                    <strong>BRISBANE, WE GOT ISSUES!</strong>
                </a>
                <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>

        <!-- white line under -->
        <div class="nav-scroller bg-white shadow-sm">
            <nav class="nav nav-underline">
                <div class="container">
                    <div class="row d-flex justify-content-between side-offset">
                        <div class="col-md-6 ">
                            <a class="nav-link active d-inline-block"
                                href="{% url 'issueTracker:projects_list' %}">Projects
                            </a>
                            <a class="nav-link active d-inline-block"
                                href="{% url 'issueTracker:my_tasks_assigned' %}">Tasks assigned to me
                            </a>
                            <a class="nav-link active d-inline-block"
                                href="{% url 'issueTracker:my_tasks_created' %}">Tasks created by me
                            </a>
                            <a class="nav-link active d-inline-block" href="{% url 'issueTracker:all_todo' %}">All todo
                            </a>
                        </div>
                        <div class="col-md-3 pr-0">
                            {% if user.is_authenticated %}
                            <ul>
                                <li class="nav-item float-right pt-1">
                                    <form class="logout" action="{% url 'accounts:logout' %}" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-secondary" type="submit">Logout</button>
                                    </form>
                                </li>
                            </ul>
                            {% else %}
                            <div class="float-right pt-1">
                                <a class="nav-link d-inline-block text-right"
                                    href="{% url 'accounts:login' %}">Login</a>
                                <a class="nav-link d-inline-block text-right"
                                    href="{% url 'accounts:signup' %}">Signup</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="text-muted my-3 pb-5">
        <div class="container">
            <div class="container">
                <p class="float-right">
                    <a href="#">Back to top</a>
                </p>
                <p>&copy; Sheng Zhuang 2019-2020</p>
                <p>more about me <a href="#">Visit my personal site.</a>
                </p>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <!-- <script>
        window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script> -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous">
    </script>

    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/1f3f07b772.js" crossorigin="anonymous"></script>

    <!-- Tempus Dominus -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js">
    </script>

    <script type="text/javascript">
        $(function () {
            $("#datetimepicker1").datetimepicker({
                format: 'YYYY-MM-DD HH:mm:ss',
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datetimepicker2").datetimepicker({
                format: 'YYYY-MM-DD HH:mm:ss',
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datetimepicker3").datetimepicker({
                format: 'YYYY-MM-DD HH:mm:ss',
            });
        });
    </script>
</body>

</html>

backend/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>this is the Home page</h1>
</body>
</html>